/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */
package io.swagger.client.api

import io.swagger.client.model.ApiResponse
import io.swagger.client.model.Device
import io.swagger.client.model.Invite
import io.swagger.client.model.Room
import io.swagger.client.model.Site
import io.swagger.client.model.Sites
import java.util.UUID
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object SiteApi {

  /**
   * Send an invite to get access to this site
   * 
   * Expected answers:
   *   code 404 :  (Site not found)
   *   code 200 : ApiResponse (response)
   * 
   * @param siteId 
   * @param invite 
   */
  def createInvite(siteId: String, invite: Invite): ApiRequest[ApiResponse] =
    ApiRequest[ApiResponse](ApiMethods.POST, "https://virtserver.swaggerhub.com/XQDEV/smartcare/1.0.0", "/sites/{site_id}/invites", "application/json")
      .withBody(invite)
      .withPathParam("site_id", siteId)
      .withErrorResponse[Unit](404)
      .withSuccessResponse[ApiResponse](200)
        /**
   * Add a device to a room
   * 
   * Expected answers:
   *   code 404 :  (Site not found)
   *   code 200 : ApiResponse (response)
   * 
   * @param siteId 
   * @param roomId 
   * @param device 
   */
  def createRoomDevice(siteId: UUID, roomId: UUID, device: Device): ApiRequest[ApiResponse] =
    ApiRequest[ApiResponse](ApiMethods.POST, "https://virtserver.swaggerhub.com/XQDEV/smartcare/1.0.0", "/sites/{site_id}/rooms/{room_id}/devices", "application/json")
      .withBody(device)
      .withPathParam("site_id", siteId)
      .withPathParam("room_id", roomId)
      .withErrorResponse[Unit](404)
      .withSuccessResponse[ApiResponse](200)
        /**
   * Create a new site
   * 
   * Expected answers:
   *   code 200 : Site (response)
   */
  def createSite(): ApiRequest[Site] =
    ApiRequest[Site](ApiMethods.POST, "https://virtserver.swaggerhub.com/XQDEV/smartcare/1.0.0", "/sites", "application/json")
      .withSuccessResponse[Site](200)
        /**
   * Create room for a site
   * 
   * Expected answers:
   *   code 404 :  (Site not found)
   *   code 200 : ApiResponse (response)
   * 
   * @param siteId 
   * @param room 
   */
  def createSiteRoom(siteId: UUID, room: Room): ApiRequest[ApiResponse] =
    ApiRequest[ApiResponse](ApiMethods.POST, "https://virtserver.swaggerhub.com/XQDEV/smartcare/1.0.0", "/sites/{site_id}/rooms", "application/json")
      .withBody(room)
      .withPathParam("site_id", siteId)
      .withErrorResponse[Unit](404)
      .withSuccessResponse[ApiResponse](200)
        /**
   * Delete a single invite of a site
   * 
   * Expected answers:
   *   code 404 :  (Invite not found)
   *   code 200 : ApiResponse (response)
   * 
   * @param inviteId 
   * @param siteId 
   */
  def deleteInvite(inviteId: String, siteId: String): ApiRequest[ApiResponse] =
    ApiRequest[ApiResponse](ApiMethods.DELETE, "https://virtserver.swaggerhub.com/XQDEV/smartcare/1.0.0", "/sites/{site_id}/invites/{invite_id}", "application/json")
      .withPathParam("invite_id", inviteId)
      .withPathParam("site_id", siteId)
      .withErrorResponse[Unit](404)
      .withSuccessResponse[ApiResponse](200)
        /**
   * Delete the device from the room
   * 
   * Expected answers:
   *   code 404 :  (Site not found)
   *   code 200 : ApiResponse (response)
   * 
   * @param siteId 
   */
  def deleteRoomDevice(siteId: UUID): ApiRequest[ApiResponse] =
    ApiRequest[ApiResponse](ApiMethods.DELETE, "https://virtserver.swaggerhub.com/XQDEV/smartcare/1.0.0", "/sites/{site_id}/rooms/{room_id}/devices/{device_id}", "application/json")
      .withPathParam("site_id", siteId)
      .withErrorResponse[Unit](404)
      .withSuccessResponse[ApiResponse](200)
        /**
   * 
   * 
   * Expected answers:
   *   code 404 :  (Site not found)
   *   code 200 : ApiResponse (response)
   * 
   * @param siteId 
   */
  def deleteSite(siteId: UUID): ApiRequest[ApiResponse] =
    ApiRequest[ApiResponse](ApiMethods.DELETE, "https://virtserver.swaggerhub.com/XQDEV/smartcare/1.0.0", "/sites/{site_id}", "application/json")
      .withPathParam("site_id", siteId)
      .withErrorResponse[Unit](404)
      .withSuccessResponse[ApiResponse](200)
        /**
   * Delete the room
   * 
   * Expected answers:
   *   code 404 :  (Site not found)
   *   code 200 : ApiResponse (response)
   * 
   * @param siteId 
   */
  def deleteSiteRoom(siteId: UUID): ApiRequest[ApiResponse] =
    ApiRequest[ApiResponse](ApiMethods.DELETE, "https://virtserver.swaggerhub.com/XQDEV/smartcare/1.0.0", "/sites/{site_id}/rooms/{room_id}", "application/json")
      .withPathParam("site_id", siteId)
      .withErrorResponse[Unit](404)
      .withSuccessResponse[ApiResponse](200)
        /**
   * Get a single invite of a site
   * 
   * Expected answers:
   *   code 404 :  (Site not found)
   *   code 200 : Invite (response)
   * 
   * @param inviteId 
   * @param siteId 
   */
  def getInvite(inviteId: String, siteId: String): ApiRequest[Invite] =
    ApiRequest[Invite](ApiMethods.GET, "https://virtserver.swaggerhub.com/XQDEV/smartcare/1.0.0", "/sites/{site_id}/invites/{invite_id}", "application/json")
      .withPathParam("invite_id", inviteId)
      .withPathParam("site_id", siteId)
      .withErrorResponse[Unit](404)
      .withSuccessResponse[Invite](200)
        /**
   * Get invites for a single site
   * 
   * Expected answers:
   *   code 404 :  (Site not found)
   *   code 200 :  (response)
   * 
   * @param siteId 
   */
  def getInvites(siteId: String): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.GET, "https://virtserver.swaggerhub.com/XQDEV/smartcare/1.0.0", "/sites/{site_id}/invites", "application/json")
      .withPathParam("site_id", siteId)
      .withErrorResponse[Unit](404)
      .withSuccessResponse[Unit](200)
        /**
   * Get a device of a room
   * 
   * Expected answers:
   *   code 404 :  (Site not found)
   *   code 200 :  (response)
   * 
   * @param siteId 
   * @param roomId 
   * @param deviceId 
   */
  def getRoomDevice(siteId: UUID, roomId: UUID, deviceId: UUID): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.GET, "https://virtserver.swaggerhub.com/XQDEV/smartcare/1.0.0", "/sites/{site_id}/rooms/{room_id}/devices/{device_id}", "application/json")
      .withPathParam("site_id", siteId)
      .withPathParam("room_id", roomId)
      .withPathParam("device_id", deviceId)
      .withErrorResponse[Unit](404)
      .withSuccessResponse[Unit](200)
        /**
   * Get the devices of a room
   * 
   * Expected answers:
   *   code 404 :  (Site not found)
   *   code 200 :  (response)
   * 
   * @param siteId 
   * @param roomId 
   */
  def getRoomDevices(siteId: UUID, roomId: UUID): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.GET, "https://virtserver.swaggerhub.com/XQDEV/smartcare/1.0.0", "/sites/{site_id}/rooms/{room_id}/devices", "application/json")
      .withPathParam("site_id", siteId)
      .withPathParam("room_id", roomId)
      .withErrorResponse[Unit](404)
      .withSuccessResponse[Unit](200)
        /**
   * Gets a single site by its site id
   * 
   * Expected answers:
   *   code 404 :  (Site not found)
   *   code 200 : Site (response)
   * 
   * @param siteId 
   */
  def getSite(siteId: UUID): ApiRequest[Site] =
    ApiRequest[Site](ApiMethods.GET, "https://virtserver.swaggerhub.com/XQDEV/smartcare/1.0.0", "/sites/{site_id}", "application/json")
      .withPathParam("site_id", siteId)
      .withErrorResponse[Unit](404)
      .withSuccessResponse[Site](200)
        /**
   * Get a room of a site
   * 
   * Expected answers:
   *   code 404 :  (Site not found)
   *   code 200 :  (response)
   * 
   * @param siteId 
   * @param roomId 
   */
  def getSiteRoom(siteId: UUID, roomId: UUID): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.GET, "https://virtserver.swaggerhub.com/XQDEV/smartcare/1.0.0", "/sites/{site_id}/rooms/{room_id}", "application/json")
      .withPathParam("site_id", siteId)
      .withPathParam("room_id", roomId)
      .withErrorResponse[Unit](404)
      .withSuccessResponse[Unit](200)
        /**
   * Get the rooms of a site
   * 
   * Expected answers:
   *   code 404 :  (Site not found)
   *   code 200 :  (response)
   * 
   * @param siteId 
   */
  def getSiteRooms(siteId: UUID): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.GET, "https://virtserver.swaggerhub.com/XQDEV/smartcare/1.0.0", "/sites/{site_id}/rooms", "application/json")
      .withPathParam("site_id", siteId)
      .withErrorResponse[Unit](404)
      .withSuccessResponse[Unit](200)
        /**
   * Get all sites for the logged in user
   * 
   * Expected answers:
   *   code 200 : Sites (response)
   */
  def getSites(): ApiRequest[Sites] =
    ApiRequest[Sites](ApiMethods.GET, "https://virtserver.swaggerhub.com/XQDEV/smartcare/1.0.0", "/sites", "application/json")
      .withSuccessResponse[Sites](200)
        /**
   * 
   * 
   * Expected answers:
   *   code 404 :  (Site not found)
   *   code 200 : ApiResponse (response)
   * 
   * @param siteId 
   */
  def updateSite(siteId: UUID): ApiRequest[ApiResponse] =
    ApiRequest[ApiResponse](ApiMethods.PUT, "https://virtserver.swaggerhub.com/XQDEV/smartcare/1.0.0", "/sites/{site_id}", "application/json")
      .withPathParam("site_id", siteId)
      .withErrorResponse[Unit](404)
      .withSuccessResponse[ApiResponse](200)
        /**
   * 
   * 
   * Expected answers:
   *   code 404 :  (Site not found)
   *   code 200 : ApiResponse (response)
   * 
   * @param siteId 
   */
  def updateSiteAttributes(siteId: UUID): ApiRequest[ApiResponse] =
    ApiRequest[ApiResponse](ApiMethods.PATCH, "https://virtserver.swaggerhub.com/XQDEV/smartcare/1.0.0", "/sites/{site_id}", "application/json")
      .withPathParam("site_id", siteId)
      .withErrorResponse[Unit](404)
      .withSuccessResponse[ApiResponse](200)
        /**
   * Create room for a site
   * 
   * Expected answers:
   *   code 404 :  (Site not found)
   *   code 200 : ApiResponse (response)
   * 
   * @param siteId 
   * @param room 
   */
  def updateSiteRoom(siteId: UUID, room: Room): ApiRequest[ApiResponse] =
    ApiRequest[ApiResponse](ApiMethods.PUT, "https://virtserver.swaggerhub.com/XQDEV/smartcare/1.0.0", "/sites/{site_id}/rooms/{room_id}", "application/json")
      .withBody(room)
      .withPathParam("site_id", siteId)
      .withErrorResponse[Unit](404)
      .withSuccessResponse[ApiResponse](200)
        /**
   * Update the rooms attributes
   * 
   * Expected answers:
   *   code 404 :  (Site not found)
   *   code 200 : ApiResponse (response)
   * 
   * @param siteId 
   * @param room 
   */
  def updateSiteRoomAttributes(siteId: UUID, room: Room): ApiRequest[ApiResponse] =
    ApiRequest[ApiResponse](ApiMethods.PATCH, "https://virtserver.swaggerhub.com/XQDEV/smartcare/1.0.0", "/sites/{site_id}/rooms/{room_id}", "application/json")
      .withBody(room)
      .withPathParam("site_id", siteId)
      .withErrorResponse[Unit](404)
      .withSuccessResponse[ApiResponse](200)
      

}

