/**
 * @fileoverview AUTOMATICALLY GENERATED service for API.Client.DeviceApi.
 * Do not edit this file by hand or your changes will be lost next time it is
 * generated.
 *
 * The API for the AAL IOT project
 * Version: 1.0.0
 * Generated by: class io.swagger.codegen.languages.JavascriptClosureAngularClientCodegen
 */
goog.provide('API.Client.DeviceApi');

goog.require('API.Client.ApiResponse');
goog.require('API.Client.Device');
goog.require('API.Client.DeviceData');
goog.require('API.Client.Event');
goog.require('API.Client.UUID');

/**
 * @constructor
 * @param {!angular.$http} $http
 * @param {!Object} $httpParamSerializer
 * @param {!angular.$injector} $injector
 * @struct
 */
API.Client.DeviceApi = function($http, $httpParamSerializer, $injector) {
  /** @private {!string} */
  this.basePath_ = $injector.has('DeviceApiBasePath') ?
                   /** @type {!string} */ ($injector.get('DeviceApiBasePath')) :
                   'https://virtserver.swaggerhub.com/XQDEV/smartcare/1.0.0';

  /** @private {!Object<string, string>} */
  this.defaultHeaders_ = $injector.has('DeviceApiDefaultHeaders') ?
                   /** @type {!Object<string, string>} */ (
                       $injector.get('DeviceApiDefaultHeaders')) :
                   {};

  /** @private {!angular.$http} */
  this.http_ = $http;

  /** @package {!Object} */
  this.httpParamSerializer = $injector.get('$httpParamSerializer');
}
API.Client.DeviceApi.$inject = ['$http', '$httpParamSerializer', '$injector'];

/**
 * 
 * Register a new device
 * @param {!Device} device 
 * @param {!angular.$http.Config=} opt_extraHttpRequestParams Extra HTTP parameters to send.
 * @return {!angular.$q.Promise<!API.Client.ApiResponse>}
 */
API.Client.DeviceApi.prototype.createDevice = function(device, opt_extraHttpRequestParams) {
  /** @const {string} */
  var path = this.basePath_ + '/devices';

  /** @type {!Object} */
  var queryParameters = {};

  /** @type {!Object} */
  var headerParams = angular.extend({}, this.defaultHeaders_);
  // verify required parameter 'device' is set
  if (!device) {
    throw new Error('Missing required parameter device when calling createDevice');
  }
  /** @type {!Object} */
  var httpRequestParams = {
    method: 'POST',
    url: path,
    json: true,
    data: device,
        params: queryParameters,
    headers: headerParams
  };

  if (opt_extraHttpRequestParams) {
    httpRequestParams = angular.extend(httpRequestParams, opt_extraHttpRequestParams);
  }

  return (/** @type {?} */ (this.http_))(httpRequestParams);
}

/**
 * 
 * Append new data for a device
 * @param {!API.Client.UUID} deviceId 
 * @param {!DeviceData} deviceData 
 * @param {!angular.$http.Config=} opt_extraHttpRequestParams Extra HTTP parameters to send.
 * @return {!angular.$q.Promise<!API.Client.ApiResponse>}
 */
API.Client.DeviceApi.prototype.createDeviceData = function(deviceId, deviceData, opt_extraHttpRequestParams) {
  /** @const {string} */
  var path = this.basePath_ + '/devices/{device_id}/data'
      .replace('{' + 'device_id' + '}', String(deviceId));

  /** @type {!Object} */
  var queryParameters = {};

  /** @type {!Object} */
  var headerParams = angular.extend({}, this.defaultHeaders_);
  // verify required parameter 'deviceId' is set
  if (!deviceId) {
    throw new Error('Missing required parameter deviceId when calling createDeviceData');
  }
  // verify required parameter 'deviceData' is set
  if (!deviceData) {
    throw new Error('Missing required parameter deviceData when calling createDeviceData');
  }
  /** @type {!Object} */
  var httpRequestParams = {
    method: 'POST',
    url: path,
    json: true,
    data: deviceData,
        params: queryParameters,
    headers: headerParams
  };

  if (opt_extraHttpRequestParams) {
    httpRequestParams = angular.extend(httpRequestParams, opt_extraHttpRequestParams);
  }

  return (/** @type {?} */ (this.http_))(httpRequestParams);
}

/**
 * 
 * Append new data for a device
 * @param {!API.Client.UUID} deviceId 
 * @param {!Event} device 
 * @param {!angular.$http.Config=} opt_extraHttpRequestParams Extra HTTP parameters to send.
 * @return {!angular.$q.Promise<!API.Client.ApiResponse>}
 */
API.Client.DeviceApi.prototype.createDeviceEvent = function(deviceId, device, opt_extraHttpRequestParams) {
  /** @const {string} */
  var path = this.basePath_ + '/devices/{device_id}/events'
      .replace('{' + 'device_id' + '}', String(deviceId));

  /** @type {!Object} */
  var queryParameters = {};

  /** @type {!Object} */
  var headerParams = angular.extend({}, this.defaultHeaders_);
  // verify required parameter 'deviceId' is set
  if (!deviceId) {
    throw new Error('Missing required parameter deviceId when calling createDeviceEvent');
  }
  // verify required parameter 'device' is set
  if (!device) {
    throw new Error('Missing required parameter device when calling createDeviceEvent');
  }
  /** @type {!Object} */
  var httpRequestParams = {
    method: 'POST',
    url: path,
    json: true,
    data: device,
        params: queryParameters,
    headers: headerParams
  };

  if (opt_extraHttpRequestParams) {
    httpRequestParams = angular.extend(httpRequestParams, opt_extraHttpRequestParams);
  }

  return (/** @type {?} */ (this.http_))(httpRequestParams);
}

/**
 * 
 * Get Data for a device
 * @param {!API.Client.UUID} deviceId 
 * @param {!angular.$http.Config=} opt_extraHttpRequestParams Extra HTTP parameters to send.
 * @return {!angular.$q.Promise}
 */
API.Client.DeviceApi.prototype.getDeviceData = function(deviceId, opt_extraHttpRequestParams) {
  /** @const {string} */
  var path = this.basePath_ + '/devices/{device_id}/data'
      .replace('{' + 'device_id' + '}', String(deviceId));

  /** @type {!Object} */
  var queryParameters = {};

  /** @type {!Object} */
  var headerParams = angular.extend({}, this.defaultHeaders_);
  // verify required parameter 'deviceId' is set
  if (!deviceId) {
    throw new Error('Missing required parameter deviceId when calling getDeviceData');
  }
  /** @type {!Object} */
  var httpRequestParams = {
    method: 'GET',
    url: path,
    json: true,
            params: queryParameters,
    headers: headerParams
  };

  if (opt_extraHttpRequestParams) {
    httpRequestParams = angular.extend(httpRequestParams, opt_extraHttpRequestParams);
  }

  return (/** @type {?} */ (this.http_))(httpRequestParams);
}

/**
 * 
 * Get Events for a device
 * @param {!API.Client.UUID} deviceId 
 * @param {!angular.$http.Config=} opt_extraHttpRequestParams Extra HTTP parameters to send.
 * @return {!angular.$q.Promise}
 */
API.Client.DeviceApi.prototype.getDeviceEvents = function(deviceId, opt_extraHttpRequestParams) {
  /** @const {string} */
  var path = this.basePath_ + '/devices/{device_id}/events'
      .replace('{' + 'device_id' + '}', String(deviceId));

  /** @type {!Object} */
  var queryParameters = {};

  /** @type {!Object} */
  var headerParams = angular.extend({}, this.defaultHeaders_);
  // verify required parameter 'deviceId' is set
  if (!deviceId) {
    throw new Error('Missing required parameter deviceId when calling getDeviceEvents');
  }
  /** @type {!Object} */
  var httpRequestParams = {
    method: 'GET',
    url: path,
    json: true,
            params: queryParameters,
    headers: headerParams
  };

  if (opt_extraHttpRequestParams) {
    httpRequestParams = angular.extend(httpRequestParams, opt_extraHttpRequestParams);
  }

  return (/** @type {?} */ (this.http_))(httpRequestParams);
}
