goog.provide('API.Client.Invite');

/**
 * @record
 */
API.Client.Invite = function() {}

/**
 * The unique invite id
 * @type {!API.Client.UUID}
 * @export
 */
API.Client.Invite.prototype.inviteId;

/**
 * The code generated for the invite (generated by server)
 * @type {!string}
 * @export
 */
API.Client.Invite.prototype.inviteCode;

/**
 * The id of the site to which a user is invited to
 * @type {!API.Client.UUID}
 * @export
 */
API.Client.Invite.prototype.siteId;

/**
 * The email address to send the invite to
 * @type {!string}
 * @export
 */
API.Client.Invite.prototype.email;

/**
 * True if the invite has been confirmed, false if not
 * @type {!boolean}
 * @export
 */
API.Client.Invite.prototype.confirmed;

