/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class Address (
  addressId: Option[UUID],
  /* The type of the address */
  `type`: Option[AddressEnums.&#x60;Type&#x60;],
  street: Option[String],
  city: Option[String],
  postcode: Option[String],
  additionals: Option[String],
  state: Option[String],
  country: Option[String]
) extends ApiModel

object AddressEnums {

  type &#x60;Type&#x60; = &#x60;Type&#x60;.Value
  object &#x60;Type&#x60; extends Enumeration {
    val Invoice = Value("invoice")
    val Site = Value("site")
    val Registrant = Value("registrant")
  }

}

