/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class Device_device_actions (
  /* The name of the action */
  actionName: Option[String],
  /* JSON schema of the requires data for the action */
  actionSchema: Option[String]
) extends ApiModel


