/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class Invite (
  /* The unique invite id */
  inviteId: Option[UUID],
  /* The code generated for the invite (generated by server) */
  inviteCode: Option[String],
  /* The id of the site to which a user is invited to */
  siteId: Option[UUID],
  /* The email address to send the invite to */
  email: Option[String],
  /* True if the invite has been confirmed, false if not */
  confirmed: Option[Boolean]
) extends ApiModel


