/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class LoginResponse (
  /* The current status of the user */
  userStatus: Option[LoginResponseEnums.UserStatus],
  registrationInfo: Option[RegistrationInfo]
) extends ApiModel

object LoginResponseEnums {

  type UserStatus = UserStatus.Value
  object UserStatus extends Enumeration {
    val Inactive = Value("inactive")
    val Active = Value("active")
  }

}

