/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class NotificationSubscriber (
  /* Unique identifier of the notification subscriber */
  id: Option[UUID],
  /* The user id of the notification subscriber */
  userId: Option[UUID],
  /* Timestamp of the creation of the Notification subscriber (Created by server) */
  creation: Option[DateTime],
  /* Timestamp of the last update of the Notification subscriber (Created by server) */
  update: Option[DateTime],
  /* The type of the address */
  recipientType: Option[NotificationSubscriberEnums.RecipientType],
  eventTopics: Option[Seq[String]],
  /* This can be either a cell phone number or an email address, depending on the recipient_type */
  recipientTarget: Option[String],
  /* The id of the site to subscribe to */
  siteId: Option[UUID]
) extends ApiModel

object NotificationSubscriberEnums {

  type RecipientType = RecipientType.Value
  object RecipientType extends Enumeration {
    val Sms = Value("sms")
    val Email = Value("email")
    val Push = Value("push")
  }

}

