/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class Permission (
  /* Unique identifier of the customer */
  permissionId: Option[UUID],
  /* The HTTP method of the permission */
  permissionMethod: Option[PermissionEnums.PermissionMethod],
  /* The path of the permission */
  permissionPath: Option[String],
  /* Timestamp of the creation of the permission (Created by server) */
  creation: Option[DateTime],
  /* Timestamp of the last update of the permission (Created by server) */
  update: Option[DateTime]
) extends ApiModel

object PermissionEnums {

  type PermissionMethod = PermissionMethod.Value
  object PermissionMethod extends Enumeration {
    val POST = Value("POST")
    val GET = Value("GET")
    val DELETE = Value("DELETE")
    val PUT = Value("PUT")
    val PATCH = Value("PATCH")
    val HEAD = Value("HEAD")
    val OPTIONS = Value("OPTIONS")
  }

}

