/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class Role (
  /* Unique identifier of the customer */
  roleId: Option[UUID],
  /* The name of the role */
  roleName: Option[String],
  /* Timestamp of the creation of the role (Created by server) */
  creation: Option[DateTime],
  /* Timestamp of the last update of the role (Created by server) */
  update: Option[DateTime]
) extends ApiModel


