/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class Room (
  /* Unique identifier of the room */
  roomId: Option[UUID],
  /* Timestamp of the creation of the room (Created by server) */
  creation: Option[DateTime],
  /* Timestamp of the last update of the room (Created by server) */
  update: Option[DateTime],
  /* A name for identification of the room */
  roomName: Option[String],
  siteId: Option[UUID]
) extends ApiModel


