/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime

case class User (
  /* Unique identifier of the customer */
  customerId: UUID,
  creation: Option[DateTime],
  update: Option[DateTime],
  language: Option[String],
  lastLogin: Option[DateTime],
  firstName: String,
  lastName: String,
  roleId: Option[UUID],
  email: String
) extends ApiModel


